#!/bin/sh

### BEGIN INIT INFO
# Provides:          iptables
# Required-Start:    networking
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: oldstyle class iptables init wrapper
### END INIT INFO

set -e
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

iptables_command="iptables"
iptables_save="/sbin/${iptables_command}-save"
iptables_restore="/sbin/${iptables_command}-restore"
libdir=/var/lib/${iptables_command}
initd="$0"
test -x ${iptables_save} || { echo "Aborting iptables initd: no ${iptables_save} executable."; exit 1; }
test -x ${iptables_restore} || { echo "Aborting iptables initd: no ${iptables_restore} executable."; exit 1; }


initd_load() {
	ruleset="$libdir/$@"
	if ! test -f "$ruleset"; then
		echo "Aborting ${iptables_command} load: unknown ruleset, \"$@\"."
		exit 1
	fi
	echo -n "Loading ${iptables_command} ruleset: load \"$@\""
	$iptables_restore < "$ruleset"
	echo "."
}


initd_save() {
	ruleset="${libdir}/$@"
	echo -n "Savinging ${iptables_command} ruleset: save \"$@\""
	$iptables_save | sed '/^:/s@\[[0-9]\{1,\}:[0-9]\{1,\}\]@[0:0]@g' > "$ruleset"
	echo "."
}


usage () {
	current="$(ls -m ${libdir})"
	cat << END
$initd options:
	start|restart|reload|force-reload
		load the "active" ruleset
	save <ruleset>
		save the current ruleset
	load <ruleset>
		load a ruleset
	stop
		load the "inactive" ruleset

Saved rulesets:
	$current
END
}


case "$1" in
	start|restart|reload|force-reload)
		initd_load active
	;;
	stop)
		initd_load inactive
	;;
	save)
		shift
		initd_save "$@"
	;;
	load)
		shift
		initd_load "$@"
	;;
	*)
		if test "$@"; then
			echo "Aborting ${iptables_command} initd: unknown command(s): \"$@\"."
		fi
		usage
	 ;;
esac

exit 0
